### ISSUE TITLE
When opening the project in Unity, regardless of the platform (Windows or Mac), the scripts are missing from the game objects.

### ISSUE THREAD

**Issue by prasanthsasikumar** [microsoft/LLMR#3]
Steps to Reproduce:
1. Clone the GitHub repository using GitHub Desktop tool.
2. Open the project in Unity (version 2022.3.11f1, recommended version for the project).
3. Install the Roslyn compiler using the package manager.
4. Observe that scripts are missing from game objects upon project opening.

Additional Information:
- The issue persists across different cloning methods(downloading zip from github) and Unity versions (including 2022.3.8f1 on Windows and Mac).
- An error message consistently appears at RunExperimentsUpdated.cs(410,30), which can be temporarily resolved by adding a "void" at line 440 in ChatCompilationModuleManager.

Possible Cause:
Based on research, the issue could be related to improper meta file uploading.

Actions Taken:
I have tried the following methods to resolve the issue:
- Cloning the repository using GitHub Desktop tool on both Windows and Mac.
- Using recommended Unity version 2022.3.11f1.
- Ensuring the Roslyn compiler is installed.
- Google search suggest that one potential issue could be wrongly uploaded meta file which could be the reasons for the missing script files in the scene objects.
<img width="1509" alt="Screenshot 2024-04-09 at 5 11 07 PM" src="https://github.com/microsoft/LLMR/assets/12469127/18e87ce0-32a5-42d0-bb85-489de4bd1c9b">

**Comment by diegomazala** [comment]
+1
Same here

**Comment by jessvb** [comment]
+1 - Same thing on my end

**Comment by JiangongChen** [comment]
+1
The same issue

**Comment by LLM4MR** [comment]
Looking into this issue! Will update once I find a solution

**Comment by Kappa666** [comment]
Looking into this and will update once we figure it out!

**Comment by Kappa666** [comment]
While am working on a solution, here's a packaged version that hopefully bypasses these issues. 
[LLMR.zip](https://github.com/microsoft/LLMR/files/14953527/LLMR.zip)

**Comment by davidhu2019** [comment]
.meta files are missing for this project. The .gitignore file used in this repo is for VisualStudio, which ignores .meta files at line 76. Please consider delete that line, or use [Unit.gitignore](https://github.com/github/gitignore/blob/main/Unity.gitignore).

**Comment by Kappa666** [comment]
@davidhu2019 Thanks, I'm not sure how the wrong .gitignore snuck in, but that was the source of the problem - my testing suggests the issue has been fixed and will close it for now.
