### ISSUE TITLE
Builder generates duplicated code so that the compiler reports error.

### ISSUE THREAD

**Issue by tyleeeeee** [microsoft/LLMR#5]
Hi all,

I want to reproduce this repo, but I've encountered some problems.
(My Unity version is 2022.3.11f1 and I also installed the Roslyn compiler.)

There's always a loop between the Builder and Compiler. I found that the code generated by the Builder is duplicated each time, so that the compiler always reports an error, even after the Inspector gives a success verdict.

![螢幕擷取畫面 2024-05-21 173754](https://github.com/microsoft/LLMR/assets/106388928/3c784d84-419f-479f-be0e-003b25a2194b)

![螢幕擷取畫面 2024-05-21 155001](https://github.com/microsoft/LLMR/assets/106388928/49596968-2b71-41ca-aff3-492d3ce3cf78)

**Comment by Kappa666** [comment]
Sorry for the late response here. I've reproduced this issue and found that it's due to an update in the OpenAI API dependency that somehow sneaked in. Will update the Chatbot.cs file (just 4 lines of change) and shift the repo to depend on the newest version of the OpenAI package asap.

**Comment by Kappa666** [comment]
Updated the repo with the new dependency, which should fix the issue.
